dist: xenial
sudo: required
language: node_js
node_js:
  - "node"
before_install:
  - |
    sudo dpkg --add-architecture i386
    sudo add-apt-repository -y ppa:mc3man/testing6
    sudo apt-get -y update
    sudo apt-get install -y libc6:i386 libmpv-dev
  - |
    cd ~
    wget https://github.com/Kagami/nacl_sdk/archive/master.zip && unzip master.zip
    nacl_sdk-master/naclsdk update
    export NACL_SDK_ROOT=$HOME/nacl_sdk-master/pepper_49
    cd -
  # Force compilation of addon.
  - sed -i '/"_from":/d' package.json
notifications:
  email:
    on_success: never
